// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#r "../../packages/Microsoft.Owin.2.0.2/lib/net45/Microsoft.Owin.dll"
#r "../../packages/Newtonsoft.Json.6.0.4/lib/net45/Newtonsoft.Json.dll"
#r "../../packages/Owin.1.0/lib/net40/Owin.dll"
#r "System.Core.dll"
#r "System.dll"
#r "System.Net.Http.dll"
#r "../../packages/Microsoft.AspNet.WebApi.Client.5.2.3/lib/net45/System.Net.Http.Formatting.dll"
#r "System.Numerics.dll"
#r "../../packages/Microsoft.AspNet.WebApi.Core.5.2.3/lib/net45/System.Web.Http.dll"
#r "../../packages/Microsoft.AspNet.WebApi.Owin.5.2.3/lib/net45/System.Web.Http.Owin.dll"
#r "../../packages/EventStore.Client.3.7.0/lib/net40/EventStore.ClientAPI.dll"
#r "../../packages/RavenDB.Client.3.0.30143/lib/net45/Raven.Abstractions.dll"
#r "../../packages/RavenDB.Client.3.0.30143/lib/net45/Raven.Client.Lightweight.dll"
#r "System.ComponentModel.Composition.dll"
#r "../../TaskManager.Domain/bin/Debug/TaskManager.Domain.dll"